### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by cherinyy** [bangbang93/lmbtfy.cn#1]
这是http下
GET http://auth.bangbang93.com/sina/short_url.php?url=http://www.lmbtfy.cn/?%E7…BE%E5%BA%A6%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BD%A0%E5%B0%B1%E7%9F%A5%E9%81%93

XMLHttpRequest cannot load http://auth.bangbang93.com/sina/short_url.php?url=http://www.lmbtfy.cn/?%E7…BE%E5%BA%A6%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BD%A0%E5%B0%B1%E7%9F%A5%E9%81%93. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.lmbtfy.cn' is therefore not allowed access. The response had HTTP status code 404.
![2](https://cloud.githubusercontent.com/assets/9050713/19411038/3eb58890-932c-11e6-8f22-e9b22b632686.png)

这是https下

Mixed Content: The page at 'https://www.lmbtfy.cn/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://auth.bangbang93.com/sina/short_url.php?url=https://www.lmbtfy.cn/?%E…BE%E5%BA%A6%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BD%A0%E5%B0%B1%E7%9F%A5%E9%81%93'. This request has been blocked; the content must be served over HTTPS.

XMLHttpRequest cannot load http://auth.bangbang93.com/sina/short_url.php?url=https://www.lmbtfy.cn/?%E…BE%E5%BA%A6%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BD%A0%E5%B0%B1%E7%9F%A5%E9%81%93. Failed to start loading.

![1](https://cloud.githubusercontent.com/assets/9050713/19411036/12b8c108-932c-11e6-8eac-2ccb9f49faef.png)

**Comment by bangbang93** [comment]
webserver昨晚升级挂了，刚刚重新配了一下

**Comment by bangbang93** [comment]
resolved
