### ISSUE TITLE
微信分享会自动在链接最后添加来源信息

### ISSUE THREAD

**Issue by faketrader** [bangbang93/lmbtfy.cn#2]
手机端使用微信分享时，会自动在链接最后加入来源信息，导致分享后的搜索关键词发生变化
例如，搜索 `如何使用百度`：
生成的链接为：<https://lmbtfy.cn/?%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%99%BE%E5%BA%A6>
分享后的链接变成：<https://lmbtfy.cn/?%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%99%BE%E5%BA%A6&from=singlemessage&isappinstalled=0>

类似的网站使用的是 `?q=<关键词>` 的格式，不会产生错误

**Comment by bangbang93** [comment]
本来是想偷懒不parse query的……

**Comment by bangbang93** [comment]
fixed
